from collections.abc import Callable
from typing import Hashable, Any, Literal, Mapping


### HOW TO CREATE KEY-FUNCTION ###
#
# Just create a function, but don't add any parameters except:
# w     - Window (useful for changing elements)
# e     - Event (Event-key, if you set any)
# v     - Value-"dict"
# val   - Value (Value of the event-element)
# elem  - Element (Element that caused the event)
# args  - Arguments generated by the tkinter-event
#
# Just set all of these parameters you need, they will be filled in accordingly.
# Their order doesn't matter.

### Some useful key-functions to use in your layout.


def copy_value_to(to_key: Hashable) -> Callable:
    """
    Copies the value to the specified key
    :param to_key: Element-key to copy to
    :return:
    """
    def fkt(v, val):
        v[to_key] = val

    return fkt

def copy_value_from(from_key: Hashable) -> Callable:
    """
    Copies the value from the specified key to the calling element
    :param from_key: Element-key to copy from
    :return:
    """
    def fkt(v, elem):
        elem.value = v[from_key]

    return fkt

def set_value_to(new_value: Any = "", elem_key: str = None) -> Callable:
    """
    Sets the value of an element.

    If you provide elem_key, that element will be changed.
    If not, the calling element will be changed.

    To clear the value of the calling element, just don't pass anything: set_value_to()

    :param elem_key: This element will be changed
    :param new_value: The element will be set to this value
    :return:
    """
    if elem_key is not None:
        def temp(v):
            v[elem_key] = new_value
    else:
        def temp(elem):
            elem.value = new_value

    return temp

def cycle_value_of(key: Hashable, *values: Any) -> Callable:
    """
    Every time this gets called, the next value is written to key
    IT WILL START AT THE SECOND VALUE, so it's a good idea to set the initial element-value as the first value.

    :param key: Element to change
    :param values: values you want to cycle
    :return:
    """
    n = 0
    val_len = len(values)

    assert val_len > 1, "You did not provide enough values for the cycle_value_of key-function"

    def temp(v):
        nonlocal n
        n += 1

        if n >= val_len:
            n = 0

        v[key] = values[n]

    return temp

def cycle_option(option: str, *values: Literal["DEFAULT"] | Any) -> Callable:
    """
    Every time this gets called, the connected element is updated roughly like this:
        elem.update(option= new_value)

    Pass "DEFAULT" as a value to make it reset to the default value

    IT WILL START AT THE SECOND VALUE, so it's a good idea to set the initial option-value as the first one.

    :param option:
    :param values: Option-values
    :return:
    """
    n = 0
    val_len = len(values)

    assert val_len > 1, "You did not provide enough values for the cycle_option key-function"

    def temp(elem):
        nonlocal n
        n += 1

        if n >= val_len:
            n = 0

        if values[n] == "DEFAULT":
            elem.update_to_default_value(option)
            return

        elem.update(**{option: values[n]})

    return temp

def set_option_at_value(option: str, values: Mapping[Hashable, Literal["DEFAULT"] | Any], default: Literal["DEFAULT"] | Any = None) -> Callable:
    """
    Change the option of this element depending on its value.

    Consider this example:
        set_option_at_value(option = "background_color", {True: "red", False: "DEFAULT"})
    On a checkbox, this colors the checkbox red if checked and changes the color back to its default value if unchecked.

    :param option: Which option to change
    :param default: Value to apply if it isn't found in the values
    :param values: dict with value:option-value-for-that-value
    :return:
    """
    def temp(elem, val):
        new_val = values.get(val, default)

        if new_val == "DEFAULT":
            elem.update_to_default_value(option)
            return

        elem.update(**{option: new_val})

    return temp


